name: working-directory Demo
on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: directory_3

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          subdirectory: directory_3
      - run: cat file_4
