name: working-directory Demo
on:
  push:
    branches:
      - main
jobs:
  demo:
    name: demo
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: directory_3
    steps:
      - uses: actions/checkout@v4
      - run: cat file_3
      - run: cat file_4
