name: cd Command Demo
on:
  push:
    branches:
      - main
jobs:
  demo:
    defaults:
      - run: |
          cd directory_1
    name: demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cat file_1
