name: working-directory Demo
on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          subdirectory: directory_3
      - run: cat file_4
