name: working-directory Demo
on:
  push:
    branches:
      - main
jobs:
  demo:
    name: demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cat file_1
        working-directory: directory_1
      - run: cat file_2
        working-directory: directory_2
